### ISSUE TITLE
Custom validator, Confirm and OnCompletion methods missing

### ISSUE THREAD

**Issue by AvinashRamalingam** [BotBuilderCommunity/botbuilder-community-dotnet#45] opened 2019-01-07 09:53 UTC
First of all, thank you for providing the Bot.Builder.Community.Dialogs.ChoiceFlow library for handling the JSON model of the form flow. Looking into it seems like there are few methods and properties like Custom validator, Confirm and OnCompletion methods missing and is really key to actually make use of the power and full potential of JSON form builder similar to V3. Are there any plans of getting this included? Thanks.

**Comment by garypretty** [comment] 2019-01-07 09:55
Hi.

Looks like you are using the wrong package. You want the FormFlow package. This signs have everything from v3.

Cheers

Gary

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AvinashRamalingam** [comment] 2019-01-08 04:47
Hi Gary,

Thanks for the response. I agree that FormFlow package has all the methods which I needed. But couldn't use them using JSON schema similar to what ChoiceFlow does. The current Community FormFlow package just supports the predefined class, what I'm looking for is to have a dynamic model utilizing JSON schema and have control towards validators, oncompletion etc similar to V3. Please suggest. Thanks.

**Comment by garypretty** [comment] 2019-01-08 19:58
it looks like the FormBuilderJson functionality has not been migrated - the migration is not something I worked on.  I can follow up and see if there is a possibility of getting this to work or if there is a specific reason it hasn't been ported.

**Comment by AvinashRamalingam** [comment] 2019-01-10 13:59
@garypretty Did you get to hear something on this request? Thanks.

**Comment by garypretty** [comment] 2019-01-15 09:35
@AvinashRamalingam Hi.  I have now confirmed that this functionality has not been ported - this was simply due to time constraints, as opposed to a technical reason.  There are currently no plans to port this - I would do this but I am struggling for time at the moment.  Please feel free to have a stab at this yourself and submit a PR though.  I am going to close this for now as we have got to the answer.

**Closed by garypretty** 2019-01-15 09:35 UTC
