### ISSUE TITLE
AdaptivCard submit action not working in waterfall dialog

### ISSUE THREAD

**Issue by saurav2107** [BotBuilderCommunity/botbuilder-community-dotnet#330] opened 2020-10-21 11:42 UTC
I am using Enterprise Bot Template for my bot.

When adding AdaptiveCard Dialog to present a input form to User having a submit button from within a waterfall dialog, which intern is called from MainDialog of enterprise bot after luis recognition, the flow is not returning to AdaptiveCard next step where I can read the result.

Below is my Adaptive Card Dialog code:
`
public RequestTrackerFormDialog(BotServices services, ConversationState conversationState, UserState userState, IBotTelemetryClient telemetryClient1, IConfiguration configuration, MicrosoftTranslator translator) :
                base(services,nameof(RequestTrackerFormDialog))
        {

            _services = services;
            _conversationState = conversationState;
            _userState = userState;
            _telemetryClient = telemetryClient1;
            this.configuration = configuration;
            _translator = translator;
            InitialDialogId = nameof(RequestTrackerFormDialog);
            WaterfallStep[] waterfallSteps = new WaterfallStep[]
            {
                GetIssueSummary,
                DisplayResultsAsync,
            };
            var complexAdaptiveCard = CreateAdaptiveCardAttachment(_cards[0]);
            var complexSettings = new AdaptiveCardPromptSettings()
            {
                Card = complexAdaptiveCard,
                PromptId = "complexCard"
            };
            AddDialog(new AdaptiveCardPrompt(DialogIds.GetIssueSummary, complexSettings));
            AddDialog(new WaterfallDialog(InitialDialogId, waterfallSteps));
        }

        private async Task<DialogTurnResult> GetIssueSummary(WaterfallStepContext stepContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            return await stepContext.PromptAsync(DialogIds.GetIssueSummary, new PromptOptions());
        }
        private async Task<DialogTurnResult> DisplayResultsAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            await stepContext.Context.SendActivityAsync("Success!");

            // Send the result to the user
            var result = (stepContext.Result as AdaptiveCardPromptResult).Data as JObject;
            var resultArray = result.Properties().Select(p => $"* **{p.Name}**: {p.Value}").ToList();
            var resultString = string.Join("\n\n", resultArray);

            await stepContext.Context.SendActivityAsync(resultString);

            return await stepContext.EndDialogAsync();
        }
`

My AdaptiveCard json

`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "Ticket Details",
      "horizontalAlignment": "Center"
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "I require few informations for creating a ticket. To abort ticket creation type Cancel anytime.",
          "wrap": true
        }
      ]
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "RichTextBlock",
          "inlines": [
            {
              "type": "TextRun",
              "text": "Issue summary:"
            }
          ]
        },
        {
          "type": "Input.Text",
          "style": "text",
          "id": "txtTicketSummary",
          "placeholder": "Issue summary"
        },
        {
          "type": "TextBlock",
          "text": "Issue details:",
          "wrap": true
        },
        {
          "type": "Input.Text",
          "style": "text",
          "isMultiline": true,
          "id": "txtTicketDetails",
          "placeholder": "ticket details",
          "maxLength": 300,
          "separator": true
        }
      ],
      "style": "emphasis",
      "bleed": true,
      "backgroundImage": {}
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch"
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Submit",
                  "id": "btnSubmit",
                  "style": "positive"
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "Cancel",
                  "id": "btnCancel",
                  "style": "destructive",
                  "data": "Cancel"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by mdrichardson** [comment] 2020-10-21 18:01
Closing here as this is a duplicate of [this issue](https://github.com/microsoft/botbuilder-dotnet/issues/4831), which is where I'll debug/fix.

**Comment by mdrichardson** [comment] 2020-10-21 18:03
@garypretty Can you close this one here? Looks like I don't have permissions for it.

**Closed** 2020-10-22 08:35 UTC
